---
title: "scDown: A pipeline to carry out the scRNASeq downstream analysis"
author: |
    | Liang Sun, Ashish Jain, Chunhui Cai, Qianyi Ma
    | Research Computing, IT Department
    | Boston Children's Hospital, Boston, MA
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    toc: true
    #number_sections: true  ## if you want number sections at each table header
    #theme: united  # many options for theme, this one is my favorite.
#bibliography: library.bib
fig_width: 8 
fig_height: 5 
vignette: >
  %\VignetteIndexEntry{TissueEnrich}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width=8, fig.height=5
)

```

Load the libraries and define universal variables for running CellChat V2
```{r, message = FALSE}
library(Seurat)
library(patchwork)
library(ComplexHeatmap)
source("/Users/chunhui/BCH_projects/scDown_pipeline/scDown/R/cellchat_functions.R")

# Set the work directory
workdir <- "/Users/chunhui/BCH_projects/scDown_pipeline/scDown_CellChatV2/"

# Seurat object
scRNAseq_seuratobj <- readRDS("/Users/chunhui/BCH_projects/scDown_pipeline/scDown/inst/extdata/p238_testdata.rds")

# Define the species: either "mouse" or "human", since CellChat and PPI database only support these two species for now
species <- "human"

# Metadata cell type column
metadata_celltype_col <- "celltype"

# Group information column (Optional, NULL by default)
metadata_condition_col <- "group"

# Pairwise condition comparisons. Default is no comparisons (Optional, NULL by default).
comparison_conditions <- list(c("CNV", "CON"), c("ASD", "CON"), c("CNV", "ASD"))
x
# Cell types of interest. (Optional, 'ALL' by default)
celltypes_of_interest <- c("Astrocyte I", "Astrocyte II", "Microglia", "OPC", "Astrocyte II", "Inh-VIP", "Neu L4", "Neu L23", "Inh-SV2C")

# Number of top pathways to show
top_n <- 10

# Run CellChat V2
run_cellchatV2(dir_cellchat, 
               seurat_obj, 
               celltype_col, 
               celltypes = "ALL", 
               species, 
               condition_col = metadata_condition_col, 
               conditions_cmp = comparison_conditions,
               top_n = 10)



```


